export const FETCH_QUESTIONS_BATCH = 'FETCH_QUESTIONS_BATCH';
export const SELECT_QUESTION       = 'SELECT_QUESTION';
export const CREATE_QUESTION       = 'CREATE_QUESTION';
export const CREATE_ANSWER         = 'CREATE_ANSWER';
